---
- name: 'Create install folder'
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | d('0755') }}"
  loop:
    - { path: "{{ swarmlet_location }}" }
    - { path: "{{ swarmlet_location_source }}" }
    - { path: "{{ swarmlet_ssh_dir }}", mode: "0700" }

- name: 'Get install script'
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/{{ swarmlet_repo }}/{{ swarmlet_version }}/install"
    dest: /tmp/swarmlet-install.sh
    mode: '0550'

- name: clean old install if needed
  become: True
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /root/.ssh
    - /tmp/swarmlet
    - "{{ swarmlet_location_source }}"

- name: Create final options
  set_fact:
    swarmlet_options:
      INSTALLATION_TYPE: "noninteractive"
      SWARMLET_INSTALL_ROOT: "{{ swarmlet_location_source }}"
      INSTALL_BRANCH: "{{ swarmlet_version }}"
      SWARMLET_USERNAME: "{{ swarmlet_login_user }}"
      SWARMLET_PASSWORD: "{{ swarmlet_password }}"
      # The authorized SSH keys for git deployments
      SSH_AUTHORIZED_KEYS: "{{ swarmlet_ssh_authorized_keys_file }}"
      # Optional: set a new hostname
      NEW_HOSTNAME: "{{ swarmlet_node_hostname }}"
      ROOT_DOMAIN: "{{ swarmlet_domain }}"
      CREATE_SWAP: "{{ swarmlet_create_swap }}"
      INSTALL_MODULES: "{{ swarmlet_modules }}"
      CA_SERVER: "{{ swarmlet_ca_env }}"

- set_fact:
    _swarmlet_options: "\
      {% for k, v in swarmlet_options.items() -%}
      {{ k }}='{{ v }}'
      {% endfor -%}"

- name: 'Install'
  environment: "{{ swarmlet_env }}"
  ansible.builtin.shell: "cat /tmp/swarmlet-install.sh | bash -s {{ _swarmlet_options }}"
  become: True
  become_user: root

- name: 'Clean'
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/swarmlet-install.sh
    - "{{ swarmlet_ssh_deploy_key }}"
  tags: [clean-swarmlet]
