---
- name: 'check'
  assert:
    that:
      - swarmlet_state in swarmlet_install_command_map

- name: 'Command exists'
  become: True
  become_user: root
  command: which swarmlet
  changed_when: false
  failed_when: false
  register: swarmlet_result

- name: 'Register installation status'
  set_fact:
    swarmlet_install_state: true
  changed_when: false
  when:
    - swarmlet_state != "absent"

- name: 'Register if uninstall is needed'
  set_fact:
    swarmlet_uninstall_state: true
  changed_when: false
  when:
    - "swarmlet_state == 'absent' or swarmlet_state == 'forcereinstall'"
    - swarmlet_result.rc == 0
    - "'swarmlet' in swarmlet_result.stdout"

- name: Copy utils
  copy:
    mode: u=rx,g=rx,o=rx
    dest: /usr/local/bin
    src: utils

- name: update password
  command: >-
    /usr/local/bin/swarm-secrets-update {{ item.stack }} {{ item.secret_name }} {{ item.data }}
  loop: "{{ swarmlet_update_secrets }}"
  when:
    - swarmlet_update_secrets | length >= 1

- include: uninstall.yml
  when: swarmlet_uninstall_state
  become: True
  become_user: root

- include: install.yml
  when:
    - swarmlet_install_state
    - "'swarmlet' not in swarmlet_result.stdout"
  become: True
  become_user: root

- include: ssh.yml
  when: swarmlet_install_state or ('swarmlet-ssh' in ansible_run_tags)
  become: True
  become_user: "{{ swarmlet_user }}"
  tags: [swarmlet-ssh]
